config/routes.rb
Rails.application.routes.draw do

	get 'welcome/index'
	
	get 'info', to: 'info#index'

	get 'contact', to: 'contact#index'
	
	resources :albums do
		resources :artworks
	end
	
	resources :exhibitions
	
	root 'welcome#index'
	

end

app/models/album.rb
class Album < ActiveRecord::Base
	validates :name, presence:true
	has_many :artworks, dependent: :destroy
end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
	belongs_to :album
	validates_presence_of :style
	mount_uploader :picture, PictureUploader
end

app/models/exhibition.rb
class Exhibition < ActiveRecord::Base
	validates_presence_of :name, :location, :duration
end

app/models/text.rb
class Text < ActiveRecord::Base
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	def index
		@albums = Album.all
	end

	def show
		@album = Album.find(params[:id])
	end
	
	def new
		@album = Album.new
	end
	
	def edit
		@album = Album.find(params[:id])
	end
	
	def create
		@album = Album.new(album_params)
		
		if @album.save
			redirect_to @album
		else
			render 'new'
		end
	end
	
	def update
		@album = Album.find(params[:id])
		
		if @album.update(album_params)
			redirect_to @album
		else
			render 'edit'
		end
	end
	
	def destroy
		@album = Album.find(params[:id])
		@album.destroy
		
		redirect_to albums_path
	end
	
	private
	def album_params
		params.require(:album).permit(:author, :name)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
	def create
		@album = Album.find(params[:album_id])
		@artwork = @album.artworks.create(artwork_params)
		if params[:picture].present?
			preloaded = Cloudinary::PreloadedFile.new(params[:picture])         
			raise "Invalid upload signature" if !preloaded.valid?
			@artwork.update_attribute(:picture, "test1")
		else
			@artwork.update_attribute(:picture, "11045491_922801141123611_5721047301384327574_n_f0fy10.jpg")
		end
		redirect_to album_path(@album)
		true
	end
	
	def show
		@artwork = Artwork.find(params[:id])
	end
	
	def destroy
		@artwork = Artwork.find(params[:id])
		@artwork.destroy
		
		redirect_to albums_path
	end
	
	attr_accessor :picture
	
	private
	def artwork_params
		params.require(:artwork).permit(:title, :author, :year, :style, :height, :width, :picture)
	end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController

	def index
		@exhibitions = Exhibition.all
	end
	
	def show
		@exhibition = Exhibition.find(params[:id])
	end
	
	def new
		@exhibition = Exhibition.new
	end

	def edit
		@exhibition = Exhibition.find(params[:id])
	end

	def create
		@exhibition = Exhibition.new(exhibition_params)
		
		if @exhibition.save
			redirect_to exhibitions_path
		else
			render 'new'
		end
	end

	def update
		@exhibition = Exhibition.find(params[:id])
		
		if @exhibition.update(exhibition_params)
			redirect_to exhibitions_path
		else
			render 'edit'
		end
	end
	
	def destroy
		@exhibition = Exhibition.find(params[:id])
		@exhibition.destroy
		
		redirect_to exhibitions_path
	end
	
	private
	def exhibition_params
		params.require(:exhibition).permit(:name, :location, :duration)
	end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def index
	@ülleinfo = Text.find_by(name: 'Ülle info')
	@raivoinfo = Text.find_by(name: 'Raivo info')
	@lisainfo = Text.find_by(name: 'Veel infot')
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
	@info = Text.find_by(name: 'Avalehe info')
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_form.html.erb
<%= form_for @album do |f| %>
  <p>
    <%= f.label :autor %><br>
    <%= f.select(:author, [['Ülle Algma-Vare'], ['Raivo Vare']]) %>
  </p>
  
  <p>
	<% if @album.errors.any? %>
		<div id="error_explanation">
			<strong>Albumi nimi ei tohi olla tühi!</strong>
		</div>
	<% end %>
    <%= f.label :albumi_nimi %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit "Salvesta" %>
  </p>
<% end %>

app/views/albums/edit.html.erb
<h1>Muuda albumit</h1>

<%= render 'form' %>

<%= link_to 'Tagasi albumite juurde', albums_path %>

app/views/albums/index.html.erb
<h1>Maalid</h1>

<%= link_to 'Lisa uus album', new_album_path %>

<h2>Ülle Algma-Vare</h2>
<% @albums.each do |album| %>
	<% if album.author == 'Ülle Algma-Vare' %>
		<%= album.name %><br>
		<%= link_to 'Vaata albumit', album_path(album) %><br>
		<%= link_to 'Muuda albumit', edit_album_path(album) %><br>
		<%= button_to 'Kustuta album', album_path(album), method: :delete, data: { confirm: "Kas oled kindel, et tahad kustutada albumi koos kõigi piltidega?" } %>
	<% end %>
<% end %>

<h2>Raivo Vare</h2>
<% @albums.each do |album| %>
	<% if album.author == 'Raivo Vare' %>
		<%= album.name %><br>
		<%= link_to 'Vaata albumit', album_path(album) %><br>
		<%= link_to 'Muuda albumit', edit_album_path(album) %><br>
		<%= button_to 'Kustuta album', album_path(album), method: :delete, data: { confirm: "Kas oled kindel, et tahad kustutada albumi koos kõigi piltidega?" } %>
	<% end %>
<% end %>

app/views/albums/new.html.erb
<h1>Uus album</h1>

<%= form_for :album, url: albums_path do |f| %>
  <p>
    <%= f.label :autor %><br>
    <%= f.select(:author, [['Ülle Algma-Vare'], ['Raivo Vare']]) %>
  </p>
  
  <p>
    <%= f.label :albumi_nimi %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/albums/show.html.erb
<%= cloudinary_js_config %> 

<p>
	(<%= @album.author %>) <strong><%= @album.name %></strong>
</p>

<h2>Teosed</h2>
<% @album.artworks.each do |work| %>
	<p>
		<strong>"<%= work.title %>"</strong><br>
		<%= work.author %><br>
		<%= work.year %><br>
		<%= work.style %><br>
		mõõtmed: <%= work.height %> x <%= work.width %><br>
		<%= work.picture %><br>
		<%= cl_image_tag(work.picture, width: 100) %>
	</p>
<% end %>

<h2>Lisa albumisse teos:</h2>
<%= form_for([@album, @album.artworks.build]) do |f| %>
  <p>
    <%= f.label :pealkiri %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :aasta %><br>
    <%= f.number_field :year %>
  </p>
  <p>
    <%= f.label :tüüp %><br>
    <%= f.text_field :style %>
  </p>
  <p>
    <%= f.label :kõrgus %><br>
    <%= f.number_field :height %>
  </p>
  <p>
    <%= f.label :laius %><br>
    <%= f.number_field :width %>
  </p>
  <p>
    <%= f.hidden_field :author, :value => @album.author %>
  </p>
  <div class="upload_button_holder">
    <%= link_to("Upload", "#", :class => "upload_button") %>
    <%= f.cl_image_upload(:picture, :return_delete_token=>true) %>
  </div>
  <!--
  <p>
	<%= f.cl_image_upload(:picture) %>
  </p>
  <p>
	<%= f.label :pilt %><br>
	<%= f.text_field :picture %>
  </p>
  <%= f.label :image, "Image:" %><br />
    <div class="upload_button_holder">
      <%= link_to "Upload", "#", class: "btn btn-primary upload_button form-control" %>
      <%= f.cl_image_upload :image, class: "form-control" %>
    </div>
    <span class="status"></span>
  -->
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Muuda albumit', edit_album_path(@album) %> | 
<%= link_to 'Tagasi albumite juurde', albums_path %>

app/views/contact/index.html.erb
<h1>Kontakt</h1>
<p>
	Helista mulle!<br>
	52 00 849
</p>
<p>
	Kirjuta mulle!<br>
	ylle.algma.vare@gmail.com
</p>
<p>
	Külasta mu Facebooki lehte või blogi!<br>
	<%= link_to 'Facebook', 'https://www.facebook.com/ulle.algmavare' %> | 
	<%= link_to 'Blogi', 'http://hetked-maalil.blogspot.com.ee/' %>
</p>

app/views/exhibitions/_form.html.erb
<%= form_for @exhibition do |f| %>

  <% if @exhibition.errors.any? %>
    <div id="error_explanation">
      <h2>
        Kõik väljad peavad olema täidetud!
      </h2>
    </div>
  <% end %>
 
  <p>
    <%= f.label :nimi %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :asukoht %><br>
    <%= f.text_field :location %>
  </p>
 
  <p>
    <%= f.label :kestus %><br>
    <%= f.text_field :duration %>
  </p>
 
  <p>
    <%= f.submit "Salvesta" %>
  </p>
<% end %>

app/views/exhibitions/edit.html.erb
<h1>Muuda näitust</h1>

<%= render 'form' %>

<%= link_to 'Tagasi näituste juurde', exhibitions_path %>

app/views/exhibitions/index.html.erb
<h1>Näitused</h1>

<%= link_to 'Lisa uus näitus', new_exhibition_path %><br>

<% @exhibitions.each do |ex| %>
	<div>
		<h3><%= ex.name %></h3>
		<%= ex.location %><br>
		<%= ex.duration %><br>
		<p>-kuulutus-</p>
		<p>-pildid-</p>
		<%= link_to 'Muuda näitust', edit_exhibition_path(ex) %><br>
		<%= button_to 'Kustuta näitus', exhibition_path(ex), method: :delete, data: { confirm: "Kas oled kindel, et tahad kustutada näituse koos kõigi andmete ja piltidega?" } %>
	</div>
<% end %>

app/views/exhibitions/new.html.erb
<h1>Uus näitus</h1>

<%= render 'form' %>

<%= link_to 'Tagasi näituste juurde', exhibitions_path %>

app/views/info/index.html.erb
<h1>Taustainfo</h1>
<!-- tekst Ülle kohta -->
<p>
	<%= @ülleinfo.content %>
</p>
--pilt--
<!-- tekst Raivo kohta -->
<p>
	<%= @raivoinfo.content %>
</p>
--pilt--
<p>
	--veel pilte--
</p>
<!-- veel teksti -->
<p>
	<%= @lisainfo.content %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Varemaalid</title>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <h1>Vare Maalid</h1>
  
  <%= link_to 'Avaleht', root_path %>
  <%= link_to 'Maalid', controller: 'albums' %>
  <%= link_to 'Näitused', controller: 'exhibitions' %>
  <%= link_to 'Taustainfo', controller: 'info' %>
  <%= link_to 'Kontakt', controller: 'contact' %>

</head>
<body>

<%= yield %>

</body>
<footer>
	<ul style="list-style-type:none">
		<!-- LIKE/SHARE -->
		<li><%= link_to 'Kontakt', controller: 'contact' %></li>
		<li>Veebilehe looja: Diana Algma</li>
		<li><%= link_to 'Logi sisse', root_path %></li>
	</ul>
	<!-- eemaldada/muuta paremaks	-->
	<p>
	  Aeg praegu: <%= Time.now %>
	</p>
</footer>
</html>

app/views/welcome/index.html.erb
<!-- Body -->
<h1>Avaleht</h1>
<!-- text -->
<p>
	<%= @info.content %>
	Rohkem infot <%= link_to 'SIIT', controller: 'info' %>.
<!-- pildid -->
<p>
	Vaata veel maale <%= link_to 'SIIT', controller: 'albums' %>.
</p>

<!-- näitus -->
<p>
	Veel infot näitustest <%= link_to 'SIIN', controller: 'exhibitions' %>.
</p>

<!-- eemaldada -->
<p>
	See koduleht pole hetkel valmis.
</p>

<p>
	Töötav lehekülg: <%= link_to 'Vare Maalid', 'http://varemaalid.webs.com' %>
</p>